#  SPDX-FileCopyrightText: Copyright 2023 Arm Limited and/or its
#  affiliates <open-source-office@arm.com>
#  SPDX-License-Identifier: Apache-2.0
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# yaml-language-server: $schema=https://raw.githubusercontent.com/Open-CMSIS-Pack/devtools/schemas/projmgr/1.5.0/tools/projmgr/schemas/cdefault.schema.json

default:
  # Note that we need AC6@6.18 or higher to compile for Corstone-310 target.
  compiler: GCC

  misc:
    - for-compiler: AC6
      CPP:
        - -std=c++14
        - -fno-exceptions
        - -Wno-license-management
        - -fno-rtti
      C:
        - -std=c99
        - -Wno-license-management
      Link:
        - --entry=Reset_Handler
        - --verbose
        - --callgraph_file='callgraph'
        - --map
        - --info=sizes,totals,unused,compression,inline,summarysizes
        - --list='diagnostics.map'
        - --diag_suppress=L6439W,L6314W,L9931W
    - for-compiler: GCC
      CPP: 
        - -std=c++11
        - -fno-rtti
        - -fno-threadsafe-statics
      C:
        - -std=gnu11
      C-CPP:
        - -mlittle-endian
        - -mthumb
        - -MD
        - -Wswitch
        - -Wvla
        - -fmessage-length=0
        - -fdata-sections
        - -ffunction-sections
        - -fno-exceptions
        - -fno-unwind-tables
        - -fomit-frame-pointer
        - -funsigned-char
      Link:
        - --specs=nano.specs
        - --specs=rdimon.specs
        - -Wl,--gc-sections
