name: FVP   # Build and execution test
on:
  workflow_dispatch:
#  pull_request:
#    branches: [main]
#  push:
#    branches: [main]
#  schedule:
#    - cron: '00 20 * * 6'

jobs:
  Test:                     # Install tools, build
    strategy:

      matrix:
        target: [
          {proj: kws,               board: AVH-SSE-300,      model: FVP_Corstone_SSE-300,            uart: mps3_board.uart0},
          {proj: kws,               board: AVH-SSE-300-U55,  model: FVP_Corstone_SSE-300_Ethos-U55,  uart: mps3_board.uart0},
          {proj: kws,               board: AVH-SSE-300-U65,  model: FVP_Corstone_SSE-300_Ethos-U65,  uart: mps3_board.uart0},
          {proj: kws,               board: AVH-SSE-310,      model: FVP_Corstone_SSE-310,            uart: mps3_board.uart0},
          {proj: kws,               board: AVH-SSE-310-U55,  model: FVP_Corstone_SSE-310,            uart: mps3_board.uart0},
          {proj: kws,               board: AVH-SSE-310-U65,  model: FVP_Corstone_SSE-310_Ethos-U65,  uart: mps3_board.uart0},
          {proj: object-detection,  board: AVH-SSE-300,      model: FVP_Corstone_SSE-300,            uart: mps3_board.uart0},
          {proj: object-detection,  board: AVH-SSE-300-U55,  model: FVP_Corstone_SSE-300_Ethos-U55,  uart: mps3_board.uart0},
          {proj: object-detection,  board: AVH-SSE-300-U65,  model: FVP_Corstone_SSE-300_Ethos-U65,  uart: mps3_board.uart0},
          {proj: object-detection,  board: AVH-SSE-310,      model: FVP_Corstone_SSE-310,            uart: mps3_board.uart0},
          {proj: object-detection,  board: AVH-SSE-310-U55,  model: FVP_Corstone_SSE-310,            uart: mps3_board.uart0},
          {proj: object-detection,  board: AVH-SSE-310-U65,  model: FVP_Corstone_SSE-310_Ethos-U65,  uart: mps3_board.uart0}
        ]

      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - name: Checkout mlek-cmsis-pack-examples
      uses: actions/checkout@v4

    - name: Install tools
      uses: ARM-software/cmsis-actions/vcpkg@v1
      with:
        config: ".ci/vcpkg-configuration.json"

    - name: Activate Arm tool license
      uses: ARM-software/cmsis-actions/armlm@v1

    - name: Build context context ${{ matrix.target.proj }}+${{ matrix.target.board }} with AC6
      run: |
         cbuild mlek.csolution.yml --update-rte --packs \
         --context ${{ matrix.target.proj }}+${{ matrix.target.board }}

    - name: Execute release context ${{ matrix.target.proj }}+${{ matrix.target.board }} on ${{ matrix.target.model }}
      if: always()
      run: |
          ${{ matrix.target.model }} \
          -a ./out/${{ matrix.target.proj }}/${{ matrix.target.board }}/Release/${{ matrix.target.proj }}.axf \
          -f ./FVP/${{ matrix.target.model }}/fvp_config.txt \
          -C ${{ matrix.target.uart }}.out_file=./out/${{ matrix.target.proj }}/${{ matrix.target.board }}/Release/fvp_stdout.log \
          --simlimit 60 --stat
          cat ./out/${{ matrix.target.proj }}/${{ matrix.target.board }}/Release/fvp_stdout.log

    - name: Execute debug context ${{ matrix.target.proj }}+${{ matrix.target.board }} on ${{ matrix.target.model }}
      if: always()
      run: |
          ${{ matrix.target.model }} \
          -a ./out/${{ matrix.target.proj }}/${{ matrix.target.board }}/Debug/${{ matrix.target.proj }}.axf \
          -f ./FVP/${{ matrix.target.model }}/fvp_config.txt \
          -C ${{ matrix.target.uart }}.out_file=./out/${{ matrix.target.proj }}/${{ matrix.target.board }}/Debug/fvp_stdout.log \
          --simlimit 60 --stat
          cat ./out/${{ matrix.target.proj }}/${{ matrix.target.board }}/Debug/fvp_stdout.log