# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-main:
    name: Sync main branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Run the Artifactory proxy
        run: |
          docker pull 104059736540.dkr.ecr.us-west-2.amazonaws.com/otg/artifactory-proxy
          docker run -d -p 8080:80 104059736540.dkr.ecr.us-west-2.amazonaws.com/otg/artifactory-proxy
          sleep 10
      - name: Download zip from Artifactory
        run: |
          curl -H "X-JFrog-Art-Api:$ARTIFACTORY_TOKEN" localhost:8080/artifactory/cmsis-reference-designs/$ARTIFACTORY_PATH/latest.zip --output /tmp/downloaded_example.zip
        env:
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
          ARTIFACTORY_PATH: ${{ secrets.ARTIFACTORY_PATH }}
          ARTIFACTORY_VERSION: latest

      - name: Clean repo files
        run: |
          git ls-files | grep -v .github | xargs --no-run-if-empty rm
      - name: Extract zip
        run: |
          7z x /tmp/downloaded_example.zip
          
          
