name: Build ML examples
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '30 22 28 * 0'

jobs:
  build-alif-targets:    
    name: Build and Run Alif Devices

    strategy:
      fail-fast: true
      matrix:
        compiler: [AC6, GCC, Clang]

    runs-on: ubuntu-latest

    env:
        ARM_UBL_ACTIVATION_CODE: ${{secrets.ARM_UBL_ACTIVATION_CODE}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup vcpkg environment
        uses: JonatanAntoni/actions/vcpkg@main
        with:
          config: vcpkg-configuration.json
          
      # - name: Activate Arm tool license
      #   run: |
      #     if [[ -n "${{ env.ARM_UBL_ACTIVATION_CODE }}" ]]; then
      #       armlm activate --code ${{ env.ARM_UBL_ACTIVATION_CODE }}
      #     else
      #       armlm activate --server https://mdk-preview.keil.arm.com --product KEMDK-COM0
      #     fi

      - name: Build object detection debug target for Alif-E7-M55-HP
        if: always() && matrix.compiler == 'AC6'
        run: cbuild mlek.csolution.yml --update-rte --packs --schema --context object-detection.Debug+Alif-E7-M55-HP --toolchain ${{ matrix.compiler }}

      - name: Build KWS debug target Alif-E7-M55-HE
        if: always() && matrix.compiler == 'AC6'
        run: cbuild mlek.csolution.yml --update-rte --packs --schema --context kws.Debug+Alif-E7-M55-HE --toolchain ${{ matrix.compiler }}

      - name: Deactivate Arm tool license
        if: always()
        run: |
          if [[ -n "${{ env.ARM_UBL_ACTIVATION_CODE }}" ]]; then
            armlm deactivate --code ${{ env.ARM_UBL_ACTIVATION_CODE }}
          else
            armlm deactivate --product KEMDK-COM0
          fi