name: HW   # Hardware build test
on:
  workflow_dispatch:

jobs:
  Build:                     # Install tools, build

    strategy:

      matrix:
        target: [
          {proj: kws, board: FRDM-K64F},
          {proj: kws, board: STM32F746-DISCO}
          # {proj: kws, board: Alif-E7-M55-HP},
          # {proj: object-detection, board: Alif-E7-M55-HP}
        ]

      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout mlek-cmsis-pack-examples
        uses: actions/checkout@v4

      - name: Install tools
        uses: ARM-software/cmsis-actions/vcpkg@v1
        with:
          config: ".ci/vcpkg-configuration.json"

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1

      - name: Build mlek contexts with AC6
        run: |
            cbuild mlek.csolution.yml --update-rte --packs \
            --context ${{ matrix.target.proj }}+${{ matrix.target.board }}

      - name: Upload build Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target.proj }}_${{ matrix.target.board }}_AC6
          path: |
            ./out/${{ matrix.target.proj }}/${{ matrix.target.board }}/
          retention-days: 1