name: Test-Version-2   # BSP Examples
on:
  workflow_dispatch:

jobs:
  Test-Examples:                     # Install tools, build 
    strategy:

      matrix:
        target: [
          {proj: kws, board: AVH-SSE-300},
          {proj: kws, board: AVH-SSE-300-U55},
          {proj: kws, board: AVH-SSE-300-U65},
          {proj: kws, board: AVH-SSE-310},
          {proj: kws, board: AVH-SSE-310-U55},
          {proj: kws, board: AVH-SSE-310-U65},
          {proj: kws, board: FRDM-K64F},
          {proj: kws, board: STM32F746-DISCO},

          {proj: object-detection, board: AVH-SSE-300},
          {proj: object-detection, board: AVH-SSE-300-U55},
          {proj: object-detection, board: AVH-SSE-300-U65},
          {proj: object-detection, board: AVH-SSE-310},
          {proj: object-detection, board: AVH-SSE-310-U55},
          {proj: object-detection, board: AVH-SSE-310-U65}
        ]

      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout mlek-cmsis-pack-examples
        uses: actions/checkout@v4

      - name: Install tools
        uses: ARM-software/cmsis-actions/vcpkg@v1
        with:
          config: ".ci/vcpkg-configuration.json"

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1

      - name: Build mlek contexts with AC6
        if: always()
        run: |
            cbuild mlek.csolution.yml --update-rte --packs \
            --context ${{ matrix.target.proj }}+${{ matrix.target.board }}
