name: Test-Version-3   # BSP Examples
on:
  workflow_dispatch:
#  pull_request:
#    branches: [main]
#  push:
#    branches: [main]
#  schedule:
#    - cron: '00 20 * * 6'

jobs:
  Test-Examples:                     # Install tools, build
    strategy:

      matrix:
        target: [
          {proj: kws,               board: AVH-SSE-300,      type: Corstone_300,  model: FVP_Corstone_SSE-300,            fvp_board: mps3_board},
          {proj: kws,               board: AVH-SSE-300-U55,  type: Corstone_300,  model: FVP_Corstone_SSE-300_Ethos-U55,  fvp_board: mps3_board},
          {proj: kws,               board: AVH-SSE-300-U65,  type: Corstone_300,  model: FVP_Corstone_SSE-300_Ethos-U65,  fvp_board: mps3_board},
          {proj: kws,               board: AVH-SSE-310,      type: Corstone_310,  model: FVP_Corstone_SSE-310,            fvp_board: mps3_board},
          {proj: kws,               board: AVH-SSE-310-U55,  type: Corstone_310,  model: FVP_Corstone_SSE-310,            fvp_board: mps3_board},
          {proj: kws,               board: AVH-SSE-310-U65,  type: Corstone_310,  model: FVP_Corstone_SSE-310_Ethos-U65,  fvp_board: mps3_board},
          {proj: object-detection,  board: AVH-SSE-300,      type: Corstone_300,  model: FVP_Corstone_SSE-300,            fvp_board: mps3_board},
          {proj: object-detection,  board: AVH-SSE-300-U55,  type: Corstone_300,  model: FVP_Corstone_SSE-300_Ethos-U55,  fvp_board: mps3_board},
          {proj: object-detection,  board: AVH-SSE-300-U65,  type: Corstone_300,  model: FVP_Corstone_SSE-300_Ethos-U65,  fvp_board: mps3_board},
          {proj: object-detection,  board: AVH-SSE-310,      type: Corstone_310,  model: FVP_Corstone_SSE-310,            fvp_board: mps3_board},
          {proj: object-detection,  board: AVH-SSE-310-U55,  type: Corstone_310,  model: FVP_Corstone_SSE-310,            fvp_board: mps3_board},
          {proj: object-detection,  board: AVH-SSE-310-U65,  type: Corstone_310,  model: FVP_Corstone_SSE-310_Ethos-U65,  fvp_board: mps3_board}
        ]


      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - name: Checkout mlek-cmsis-pack-examples
      uses: actions/checkout@v4

    - name: Install tools
      uses: ARM-software/cmsis-actions/vcpkg@v1
      with:
        config: ".ci/vcpkg-configuration.json"

    - name: Activate Arm tool license
      uses: ARM-software/cmsis-actions/armlm@v1

    - name: Build mlek contexts with AC6
      if: always()
      run: |
         cbuild mlek.csolution.yml --update-rte --packs \
         --context ${{ matrix.target.proj }}+${{ matrix.target.board }}
