name: Test-Examples   # BSP Examples
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '00 20 * * 6'

jobs:
  Test-Examples:                     # Install tools, build 
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout mlek-cmsis-pack-examples root
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .ci

      - name: Install tools
        uses: ARM-software/cmsis-actions/vcpkg@v1
        with:
          config: "./.ci/vcpkg-configuration.json"

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1

      - name: Initialize CMSIS pack root folder
        run: |
          cpackget init https://www.keil.com/pack/index.pidx
          cpackget update-index

      - name: Install missing packs
        working-directory: ./
        run: |
          csolution list packs -s mlek.csolution.yml -m > packlist.txt
          cpackget add -f packlist.txt
          cat packlist.txt          
          rm packlist


      - name: Checkout STM32H7xx_DFP
        uses: actions/checkout@v4
        with:
          repository: Open-CMSIS-Pack/STM32H7xx_DFP
          path: ./STM32H7xx_DFP

      - name: Checkout CMSIS-Driver_STM32
        uses: actions/checkout@v4
        with:
          repository: Open-CMSIS-Pack/CMSIS-Driver_STM32
          path: ./CMSIS-Driver_STM32