name: Test-Examples   # BSP Examples
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '00 20 * * 6'

jobs:
  Test-Examples:                     # Install tools, build 
    strategy:

      matrix:
        target: [
          {proj: kws, board: AVH-SSE-300},
          {proj: kws, board: AVH-SSE-300-U55},
          {proj: kws, board: AVH-SSE-300-U65},
          {proj: kws, board: AVH-SSE-310},
          {proj: kws, board: AVH-SSE-310-U55},
          {proj: kws, board: AVH-SSE-310-U65},
          {proj: kws, board: Alif-E7-M55-HE},
          {proj: kws, board: FRDM-K64F},
          {proj: kws, board: STM32F746-DISCO},

          {proj: object-detection, board: AVH-SSE-300},
          {proj: object-detection, board: AVH-SSE-300-U55},
          {proj: object-detection, board: AVH-SSE-300-U65},
          {proj: object-detection, board: AVH-SSE-310},
          {proj: object-detection, board: AVH-SSE-310-U55},
          {proj: object-detection, board: AVH-SSE-310-U65},
          {proj: object-detection, board: Alif-E7-M55-HP}
        ]
        build: [ 
          {type: Release},
          {type: Debug}
        ]

      fail-fast: false

    runs-on: ubuntu-latest
    environment: Modification

    steps:
      - name: Checkout mlek-cmsis-pack-examples
        uses: actions/checkout@v4
        with:
          repository: Evagan2018/mlek-cmsis-pack-examples
          path: ./

      - name: Install tools
        uses: ARM-software/cmsis-actions/vcpkg@v1
        with:
          config: "./.ci/vcpkg-configuration.json"

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1

      - name: Initialize CMSIS pack root folder
        run: |
          cpackget init https://www.keil.com/pack/index.pidx
          cpackget update-index

      - name: Build mlek contexts with AC6
        if: always()
        working-directory: ./
        run: |
            cbuild mlek.csolution.yml --update-rte --packs \
            --context ${{ matrix.target.proj }}.${{ matrix.build.type }}+${{ matrix.target.board }} \
            --toolchain AC6 --rebuild