name: Test-Examples   # BSP Examples
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '00 20 * * 6'

jobs:
  Test-Examples:                     # Install tools, build 
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout mlek-cmsis-pack-examples
        uses: actions/checkout@v4
        with:
          repository: Evagan2018/mlek-cmsis-pack-examples
          path: ./

      - name: Install tools
        uses: ARM-software/cmsis-actions/vcpkg@v1
        with:
          config: "./.ci/vcpkg-configuration.json"

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1

      - name: Initialize CMSIS pack root folder
        run: |
          cpackget init https://www.keil.com/pack/index.pidx
          cpackget update-index

      - name: Install missing packs
        if: always()      
        working-directory: ./
        run: |
          csolution list packs -S mlek.csolution.yml -m > packlist.txt
          cat packlist.txt
          cpackget add --agree-embedded-license --packs-list-filename --force-reinstall packlist.txt

      - name: Upload packlist.txt as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: packlist.txt
          path: |
                ./packlist.txt
          retention-days: 1